// Code generated by hertz generator.

package cart

import (
	"Go-Mall/app/client/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addcartitemMw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}

func _getcartMw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}

func _emptycartMw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}
