// Code generated by hertz generator.

package checkout

import (
	"Go-Mall/app/client/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkout0Mw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}

func _checkoutresultMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkoutwaitingMw() []app.HandlerFunc {
	// your code...
	return nil
}
