// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "Go-Mall/app/client/biz/router/cart"
	checkout "Go-Mall/app/client/biz/router/checkout"
	order "Go-Mall/app/client/biz/router/order"
	product "Go-Mall/app/client/biz/router/product"
	user "Go-Mall/app/client/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	order.Register(r)

	checkout.Register(r)

	cart.Register(r)

	product.Register(r)

	user.Register(r)
}
