// Code generated by hertz generator.

package order

import (
	"Go-Mall/app/client/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderlistMw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeorderMw() []app.HandlerFunc {
	// 使用casbin中间件
	return []app.HandlerFunc{
		middleware.CasbinAuth.RequiresRoles("member"),
	}
}
